name = 'napatsc Personal Theme'
license = 'MIT'
licenselink = 'https://github.com/anonymaew/napatsc-personal/LICENSE'
description = 'My opinionated Hugo theme for my personal website'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/anonymaew/napatsc-personal'

# If you have a running demo of the theme
demosite = 'https://napatsc.com'

# Taxonomy terms
tags = ['blog', 'gallery', 'project']
features = ['responsive', 'dark-mode', 'light-mode', 'no-js', 'search', 'syntax-highlighting', 'multilingual', 'jpegxl']

# If the theme has a single author
[author]
  name = 'Napat Srichan'
  homepage = 'https://napatsc.com'
